name: Release ddnuts

on:
  workflow_dispatch:

jobs:
  release:
    name: Release ddnuts
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1

      - name: Build ddnuts
        run: |
          zig build
          bash ./pkg/bundle.sh

      - name: Gather Release Info
        run: |
          TAG=$(grep -m 1 -oE "\.version[[:space:]]*=[[:space:]]*\"[^,]+" "./build.zig.zon" | grep -m 1 -oE "[0-9]+([0-9]|\.)+")
          echo "TAG=v${TAG}" >> $GITHUB_ENV

      - name: Create the Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG }}
          artifacts: ./zig-out/*
